spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.98.50.35:3306/LaoBan?characterEncoding=utf8&useSSL=false
  #    虚拟机链接url:jdbc:mysql://192.168.1.106/LaoBan?characterEncoding=utf8&useSSL=false
#    服务器地址：jdbc:mysql://47.98.50.35:3306/LaoBan?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true

server:
  context-path: /laoban_back
  port: 8080
